'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Icon from '@/components/icons';
import SidePanel from '@/components/SidePanel';
import Toast, { type ToastData } from '@/components/Toast';
import { ConfirmDialog, Empty, PanelError, Pill } from '@/components/ui';
import { api, listOf } from '@/lib/api';
import { inr } from '@/lib/format';
import { durationLabel, planSummary, statusPayload } from '@/lib/packages';
import type { PackageRow } from '@/lib/types';

type Tab = 'all' | 'on' | 'off';

export default function PackagesList({ initial, notice }: { initial: PackageRow[] | null; notice?: string }) {
  const [rows, setRows] = useState<PackageRow[]>(initial ?? []);
  const [failed, setFailed] = useState(!initial);
  const [tab, setTab] = useState<Tab>('all');
  const [q, setQ] = useState('');
  const [menu, setMenu] = useState<string | null>(null);
  const [detail, setDetail] = useState<PackageRow | null>(null);
  const [confirm, setConfirm] = useState<PackageRow | null>(null);
  const [busy, setBusy] = useState(false);
  const [toast, setToast] = useState<ToastData | null>(notice ? { id: 0, msg: notice, tone: 'good' } : null);
  const nextId = useRef(1);
  const say = useCallback((msg: string, extra: Partial<ToastData> = {}) => setToast({ id: nextId.current++, msg, ...extra }), []);

  const reload = useCallback(async () => {
    const r = await api<{ result?: unknown }>('package/allAdmin');
    if (r.ok) { setRows(listOf<PackageRow>(r.body?.result)); setFailed(false); } else if (!rows.length) setFailed(true);
  }, [rows.length]);

  // The ⋯ menu closes on Escape or a click anywhere else.
  useEffect(() => {
    if (!menu) return;
    const close = (e: Event) => { if (!(e.target as HTMLElement).closest('.kebab')) setMenu(null); };
    const esc = (e: KeyboardEvent) => { if (e.key === 'Escape') setMenu(null); };
    document.addEventListener('click', close);
    document.addEventListener('keydown', esc);
    return () => { document.removeEventListener('click', close); document.removeEventListener('keydown', esc); };
  }, [menu]);

  const counts = useMemo(() => ({ all: rows.length, on: rows.filter(r => r.isActive).length, off: rows.filter(r => !r.isActive).length }), [rows]);
  const visible = useMemo(() => {
    const term = q.trim().toLowerCase();
    return rows.filter(r => (tab === 'all' || (tab === 'on') === r.isActive) && (!term || `${r.packageName} ${r.description ?? ''}`.toLowerCase().includes(term)));
  }, [rows, tab, q]);

  /** Flips Active/Inactive at once, then confirms with the server. On failure it flips back. The plans are resent (see statusPayload). */
  async function setActive(p: PackageRow, isActive: boolean, isUndo = false) {
    const apply = (v: boolean) => setRows(rs => rs.map(r => (r._id === p._id ? { ...r, isActive: v } : r)));
    apply(isActive);
    const current = { ...p, isActive: !isActive };
    const r = await api(`package/${p._id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(statusPayload(current, isActive)) },
      `Could not update “${p.packageName}”.`);
    if (!r.ok) { apply(!isActive); say(r.message, { tone: 'bad' }); return; }
    if (!isUndo) say(`“${p.packageName}” is now ${isActive ? 'Active' : 'Inactive'}.`, { undo: () => setActive({ ...p, isActive }, !isActive, true) });
    else say(`“${p.packageName}” is ${isActive ? 'Active' : 'Inactive'} again.`);
    reload(); // plan ids are regenerated by the backend on every save, so refresh them
  }

  async function remove() {
    if (!confirm) return;
    setBusy(true);
    const r = await api(`package/${confirm._id}`, { method: 'DELETE' }, `Could not delete “${confirm.packageName}”.`);
    if (r.ok) { setRows(rs => rs.filter(x => x._id !== confirm._id)); setDetail(null); say(`“${confirm.packageName}” was deleted.`); }
    else say(r.message, { tone: 'bad' });
    setBusy(false);
    setConfirm(null);
  }

  const openDetail = (p: PackageRow) => (e: React.MouseEvent) => { if (!(e.target as HTMLElement).closest('button, a')) setDetail(p); };

  return (
    <div className="card flush">
      <div className="tools">
        <label className="searchbox">
          <Icon name="search" size={16} />
          <input type="search" placeholder="Search packages" aria-label="Search packages" value={q} onChange={e => setQ(e.target.value)} />
        </label>
        <div className="tabs" role="tablist" aria-label="Filter by status">
          {([['all', 'All'], ['on', 'Active'], ['off', 'Inactive']] as const).map(([k, label]) => (
            <button key={k} type="button" role="tab" aria-selected={tab === k} onClick={() => setTab(k)}>{label}<em>{counts[k]}</em></button>
          ))}
        </div>
      </div>

      {failed && !rows.length ? (
        <PanelError onRetry={reload} busy={false} />
      ) : (
        <div className="tw flat">
          <table className="tbl pk">
            <thead><tr><th>Package</th><th>Ages</th><th>Pricing</th><th>Status</th><th className="narrow-col"><span className="sr-only">Actions</span></th></tr></thead>
            <tbody>
              {visible.map(p => {
                const s = planSummary(p.packageCosts, inr);
                return (
                  <tr key={p._id} className="clickable" onClick={openDetail(p)}>
                    <td>
                      <button type="button" className="strong-link linkbtn" onClick={() => setDetail(p)}>{p.packageName}</button>
                      <div className="desc" title={p.description || undefined}>{p.description || 'No description'}</div>
                    </td>
                    <td><span className="chip">{p.ageFrom}–{p.ageTo} yrs</span></td>
                    <td>{s ? <div className="price">{s.headline}<small>{s.detail}</small></div> : <span className="chip warn">No price yet</span>}</td>
                    <td>
                      <button type="button" className="sw" role="switch" aria-checked={p.isActive} onClick={() => setActive(p, !p.isActive)}
                              aria-label={`${p.packageName}: ${p.isActive ? 'active' : 'inactive'}. Press to ${p.isActive ? 'turn off' : 'turn on'}`}>
                        <i /><span>{p.isActive ? 'Active' : 'Inactive'}</span>
                      </button>
                    </td>
                    <td>
                      <div className="kebab">
                        <button type="button" className="btn ghost sm" aria-haspopup="menu" aria-expanded={menu === p._id} aria-label={`More actions for ${p.packageName}`}
                                onClick={e => { e.stopPropagation(); setMenu(menu === p._id ? null : p._id); }}>⋯</button>
                        {menu === p._id ? (
                          <div className="menu" role="menu">
                            <button type="button" role="menuitem" onClick={() => { setMenu(null); setDetail(p); }}>View details</button>
                            <Link role="menuitem" href={`/packages/${p._id}/edit`}>Edit</Link>
                            <Link role="menuitem" href={`/packages/new?copy=${p._id}`}>Duplicate</Link>
                            <button type="button" role="menuitem" className="dn" onClick={() => { setMenu(null); setConfirm(p); }}>Delete…</button>
                          </div>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {!visible.length ? <Empty title={rows.length ? 'No packages match' : 'No packages yet'} hint={rows.length ? 'Try a different word or switch the tab.' : 'Use “Add package” to create the first one.'} /> : null}
        </div>
      )}
      <div className="foot">Click a row to see its plans. Use the switch to turn a package on or off.</div>

      <SidePanel open={Boolean(detail)} title={detail?.packageName ?? ''} subtitle={detail ? `${detail.ageFrom}–${detail.ageTo} years` : undefined} onClose={() => setDetail(null)}
                 icon={<span className="kpi-ic teal"><Icon name="package" /></span>}
                 footer={detail ? (<><Link className="btn primary" href={`/packages/${detail._id}/edit`}>Edit</Link><Link className="btn" href={`/packages/new?copy=${detail._id}`}>Duplicate</Link><button type="button" className="btn danger-o" onClick={() => setConfirm(detail)}>Delete…</button></>) : null}>
        {detail ? (
          <>
            <Pill tone={detail.isActive ? 'good' : 'off'}>{detail.isActive ? 'Active' : 'Inactive'}</Pill>
            <section>
              <div className="sec-title">Plans</div>
              {detail.packageCosts?.length ? (
                <ul className="rows">{detail.packageCosts.map((c, i) => <li key={c._id ?? i}><span className="grow">{durationLabel(c.validity)}</span><strong>{inr(c.price)}</strong></li>)}</ul>
              ) : <p className="muted">No plans yet. Edit the package to add one.</p>}
            </section>
            <section><div className="sec-title">Description</div><p>{detail.description || 'No description'}</p></section>
          </>
        ) : null}
      </SidePanel>

      <ConfirmDialog open={Boolean(confirm)} danger busy={busy} title={`Delete “${confirm?.packageName ?? ''}”?`}
                     body="Students who already bought it keep access. It will no longer be offered to anyone." confirmLabel="Delete package" onConfirm={remove} onCancel={() => setConfirm(null)} />
      <Toast toast={toast} onClose={() => setToast(null)} />
    </div>
  );
}
